version: 1.0.3.{build}
image: Visual Studio 2015
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack Cake.FileHelpers.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath .\
artifacts:
- path: '*.nupkg'
  name: NuGet
